import Head from "next/head";
import React, { useState } from "react";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const [name, setName] = useState("");
  const router = useRouter();

  const onSubmit = () => {
    window.localStorage.setItem("name", name);
    router.push("/list");
  };

  return (
    <>
      <Head>
        <title>Chá de casa nova</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.container}>
          <h2>Seja bem-vindo(a)</h2>
          <span>Chá de casa nova</span>
          <p>Estêvão e Eduarda</p>

          <input
            type="text"
            placeholder="Digite seu nome completo"
            value={name}
            onChange={(e) => {
              setName(e.target.value);
            }}
          />
          <button
            type="button"
            onClick={() => {
              onSubmit();
            }}
          >
            Entrar
          </button>
        </div>
      </main>
    </>
  );
}
